branches:
    - main
    - refs/pull/*/merge
plugins:
- - "@semantic-release/commit-analyzer"
  - releaseRules:
    - type: refactor
      release: patch
    - scope: no-release
      release: false
- - "@semantic-release/release-notes-generator"
  - preset: angular
